name: 'Check for Incomplete Issues'

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          github-token: ${{ github.token }}
          process-only: 'issues'
